# @package _global_

# to execute this experiment run:
# python train.py experiment=example

defaults:
  - override /datamodule: arxiv_bert
  - override /lightning_model: flow_model
  - override /flow: real_nvp
  - override /callbacks: default
  - override /core: default

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

core:
  tags: ["arxiv", "bert", "maf", "flow"]
  group: "train_flow"
  seed: 0